### ISSUE TITLE
label.onClick не работает...

### ISSUE THREAD

**Issue by proofbyios** [psharanda/Atributika#65]
После ручной или пода установки не работает label.onClick
чтобы решить проблему пришлось исправить код в файле AttributedLabel.swift
с 
let highlightableDetections = text.detections.filter {
                $0.style.typedAttributes[.highlighted] != nil
            }

на
let highlightableDetections = text.detections.filter {
                $0.style.typedAttributes[.highlighted]?.count != 0
            }

После этого работает label.onClick

Но в кейсе .tag.name приходит не верное значение - p например
Из-за этого текст который помечен ссылкой - не работает.

так же есть разрывы в тексте не понятные http://joxi.ru/a2XEbLyI1GnoNA

Исправьте пожалуйста эти баги!

Все остальное работает корректно (хэштэг не проверял еще)

**Comment by psharanda** [comment]
Hi,
Code in AttributedLabel.swift looks correct. You are likely misusing `.highlighted` style type.  Please provide sample code, so I can try to reproduce your situation.

By the way, english is the only acceptable way for communication in this repository. Also you need to understand that this is open source library, there are no any obligations, you are using it at your own risk, so try to be polite.

**Comment by proofbyios** [comment]
I'm sorry. I does'n mean something bad. 

I use your example http://joxi.ru/L214QNec8bXW9m

Source code:
https://drive.google.com/file/d/1gDPyE9tqmjyZ4AAGG7_Tfk8sBHMFgNWi/view?usp=sharing

**Comment by psharanda** [comment]
Alright, now I see what happens. 
1. `$0.style.typedAttributes[.highlighted]?.count != 0` is totally incorrect because `nil` is not equal zero, so filter doesn't actually filter detections, and that is why you see `<p>` tag. You need to revert that change.
2. `.highlighted` doesn't make any sense for `all` style, because styleAll applies style for the whole string, but except detections.
```
let all = Style.font(.systemFont(ofSize: 17)).foregroundColor(.black)
            //.foregroundColor(.blue, .normal)
            .foregroundColor(.brown, .highlighted) // <---- remove this
```
3. In README, there is an example how to make detections clickable. You should follow it. To make detection clickable, it must contain at least one attribute of `.highlighted` type
```
let link = Style("a")
    .foregroundColor(.blue, .normal)
    .foregroundColor(.brown, .highlighted) // <-- detections with this style will be clickable now
```

**Comment by proofbyios** [comment]
Now it's works 

Thank you a lot

You are Genius. Your project Atributika is amazing.

**Comment by rursache** [comment]
please add 

> .foregroundColor(.brown, .highlighted) // <-- detections with this style will be clickable now

this as a requirement for clickable elements in readme on the main page
