### ISSUE TITLE
AttributedLabel's links are not clickable when Initializing it from interface builder

### ISSUE THREAD

**Issue by tbaranes** [psharanda/Atributika#69]
Thanks for that awesome and lifesaver library :)
Yesterday I encounter an issue and I'm wondering if that was normal: when initializing AttributedLabel in interface builder then configuring it in code, the links weren't clickable (but the style worked) while the same text was clickable when adding the label programatically. Any idea?

I also get a similar issue with `numberOfLines`, I had to do it programatically to get it working (won't work when configuring it from interface builder)

**Comment by psharanda** [comment]
Hi,
thanks for good words and interest in Atributika :)

Usually `AttributedLabel` just works if added using IB. Likely there is some issue with your views hierarchy. Check if there are no other views on top of AttributedLabel, or userInteraction disabled for some superview.
If nothing helps you could provide your example with reproducible bug (or add PR with test view controller embed into Demo app)

`numberOfLines` can't be set from IB since it is not marked as `@IBInspectable`. `@IBInspectable` is not added to `AttributedLabel` intentionally because of this view nature, which is supposed to be configured from code.

**Comment by tbaranes** [comment]
I ended adding it manually since it was working, but I'm gonna try again with a sample project. I will let you know how it goes.

**Comment by psharanda** [comment]
Ok I see the problem. First of all AttributedLabel is not a UILabel, so you need to add it as UIView, and then select proper custom class (actually I was not able to add it UILabel, but somehow it has Label section in your storyboard). If you add AttributedLabel as custom UIView then it will have userInteractionEnabled=true by default. But even in your storyboard you can toggle userInteractionEnabled and it starts working

**Comment by tbaranes** [comment]
Aaaah, I missed that (I didn't check the parent of `AttributedLabel`). I now also understand why `UILabel`'s `numberOfLines`wasn't working. Thanks for the explanation :)
